name: PrettyDate
author: thinkphp
current: v1.0
category: utilities
tags: [date,iso8601,time]
docs: https://github.com/thinkphp/prettydate/blob/master/Docs/PrettyDate.md
demo: http://thinkphp.github.com/prettydate/
